import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#4c4546",
        "outline": "#7e7576",
        "inverse-on-surface": "#f1f1f1",
        "background": "#ffffff",
        "on-surface": "#1a1c1c",
        "primary-container": "#1b1b1b",
        "primary": "#00b4ff",
        "on-secondary-fixed": "#1a1c1c",
        "surface-dim": "#dadada",
        "inverse-surface": "#2f3131",
        "error-container": "#ffdad6",
        "tertiary": "#000000",
        "primary-fixed-dim": "#c6c6c6",
        "error": "#ba1a1a",
        "surface-container-highest": "#e2e2e2",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-variant": "#e2e2e2",
        "on-tertiary-fixed-variant": "#464747",
        "surface": "#f9f9f9",
        "on-tertiary-container": "#848484",
        "on-primary-fixed-variant": "#474747",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "inverse-primary": "#c6c6c6",
        "tertiary-fixed": "#e4e2e2",
        "surface-tint": "#5e5e5e",
        "surface-container-high": "#e8e8e8",
        "on-primary-fixed": "#1b1b1b",
        "secondary-container": "#dfe0e0",
        "surface-container": "#eeeeee",
        "surface-bright": "#f9f9f9",
        "primary-fixed": "#e2e2e2",
        "tertiary-container": "#1b1c1c",
        "on-background": "#1a1c1c",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1b1c1c",
        "outline-variant": "#cfc4c5",
        "secondary": "#5d5f5f",
        "on-primary-container": "#848484",
        "on-secondary-container": "#616363",
        "on-primary": "#ffffff",
        "secondary-fixed": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
        full: "9999px",
      },
      spacing: {
        "section-padding": "128px",
        unit: "8px",
        margin: "64px",
        "container-max": "1440px",
        gutter: "32px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        display: ["80px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};

export default config;
